/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package koneksi;
import java.sql.*;

public class App {

    public static void main( String[] args ) throws SQLException {
        
       //create connection for a server installed in localhost, with a user "root" with no password
       try (Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost/", "postgres", null)) {
        // create a Statement
        try (Statement st = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY)){
            //execute query
            try (ResultSet rs = st.executeQuery("SELECT 'Hello World!'")) {
                //position result to first
                rs.first();
                System.out.println(rs.getString(1)); //result is "Hello World!"
            }
        }
    }
}
}
   